repos:
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      args: ["--in-place",  "--imports=clingo,clingox", "--ignore-init-module-imports", "--remove-unused-variables"]
      exclude: ^.github/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^.github/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ^.github/

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      exclude: ^.github/
